- hosts: webserver
  connection: local
  remote_user: root

  tasks:
    - name: test connection
      ping:

    - name: copy jar file to web server
      copy:
        src: ../stock-monitor-deploy/target/stock-monitor.jar
        dest: ~/stock-monitor/stock-monitor.jar