spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
  datasource:
    url: jdbc:h2:file:/Users/raphael008/IdeaProjects/stock-monitor/h2db
    username: sa
    password:
    driver-class-name: org.h2.Driver
server:
  port: 8888