- hosts: webserver
  remote_user: root
  vars:
    authorized_key_list:
      - name: root
      authorized_keys:
        - key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  tasks:
    - name: test connection
      ping: